# Introduction to python and numpy
This is a jupyter notebook. Each box on the screen is called a cell. Each cell can either contain text (such as this one) or code. Each code cell can be executed independently of other cells.
Use Shift + Enter to run a cell and move to the next one.

## Python crash course
 Taken in part from the [official python tutorials ](https://docs.python.org/3.8/tutorial/index.html)

  [Official python documentation](https://docs.python.org/3/)


In [1]:
print("Hello World!")

Hello World!


### Basic arithmetics

In [2]:
1+1 

2

In [3]:
20*2-30

10

In [4]:
8 / 5  #division always returns a floating point number

1.6

In [5]:
8//5 #floor division

1

In [6]:
17%3 #remainder of the division

2

In [7]:
2**3 #powers

8

In [8]:
# 1j is the imaginary unit
1j**2

(-1+0j)

In [9]:
(1+1j)*(1-2j) #complex multiplication

(3-1j)

### Declaring and assigning variables
Python is dynamically typed, meaning that the type (character, int, double) of a variable is inferred at runtime. Therefore you don't need to specify it when declaring variables.

In [10]:
a=2
b=5.450
c=a+b
c

7.45

### Strings

In [11]:
a="the quick brown fox jumps over the lazy dog"
print(a)

the quick brown fox jumps over the lazy dog


In [12]:
print(a[0])
print(a[-1]) # negative indices count form the end 
print(a[2:10]) # [start: stop] last index not included (i.e. 2:10 means 2,3,4,5,6,7,8,9)
print(a[2:10:2])# [start:stop:step]

t
g
e quick 
eqik


In [13]:
len(a) #length

43

### Printing

In [14]:
X=35
Y=290.39343939339

# C++ like syntax 
print("x=%d y=%.3f"%(X,Y))  

# Put variables directly in text, between curly brackets {}.
print(f"x={X} y={Y:.2e}") 

#print can also take directly objects as arguments
a=[1,2,3,4]
print(a)

x=35 y=290.393
x=35 y=2.90e+02
[1, 2, 3, 4]


### Flow control

In [15]:
#if statements
x=10
if(x>0):
    print("x is greater than zero")
elif(x==0):
    print("x is exactly zero")
else:
    print("x is negative")

x is greater than zero


In [16]:
#The range function: loop over the integers from 0 to 4
for i in range(5):
    print(i)

0
1
2
3
4


In [17]:
for i in range(5,20,2): #start,stop,step
    print(i)

5
7
9
11
13
15
17
19


In [18]:
i=0
while (i<5):
    print(i)
    i+=1

0
1
2
3
4


### Functions

In [19]:
def power(x,exp):
    return x**exp
    
power(2,3)

8

In [20]:
def volume_surface(a,b=2,c=3):#default arguments
    vol=a*b*c
    surf=a*b
    return vol,surf

volume_surface(a=2)

(12, 4)

#### Exercise(for later): 
Write a function that takes as arguments an integer  `n`, a positive float `s` and returns $$S_n(s)=\sum_{k=1}^n k^{-s} $$

In [21]:
#Solution
def truncated_zeta(n,s):
    res=0
    for i in range(1,n+1):
        res=res*(k**(-s))
    return res

## Numpy
Numpy is the main library for scientific computing. 
The strength of python lies in its libraries: without them it would be just another crappy programming language.
**One cannot learn python without learning the libraries**.

Python benefits from a very large community, so chances are someone else had the same problem as you and posted it on [Stack Overflow](https://stackoverflow.com/).

You can also use [ChatGPT](https://chat.openai.com/) or [Github Copilot](https://github.com/features/copilot) to help writing and debugging code. Just remember to check that the output makes sense!

Numpy complete tutorial and documentation:
1. [Official quickstart guide](https://numpy.org/doc/stable/user/quickstart.html)
 
2. [Official documentation](https://numpy.org/doc/1.21/)
 
 

To use `numpy` you need to import the module, using for example:

In [22]:
import numpy as np

### Vectors in python
There are two data structures to represent vectors
1. Python lists
2. Numpy arrays


In [23]:
a=[1,2,3,4] #syntax for python list
b=np.array([1,2,3,4]) #syntax for numpy array

In [24]:
a=[[1,2],[3,4]] #nested list
b=np.array([[1,2],[3,4]]) #nested list converted in 2 by 2 numpy array

### Arrays vs Lists
Many operations (e.g., accessing elements via index, iterating over elements, appending, removing ,concatenating,...) are available both in lists and arrays.
We will describe these things only for numpy arrays, but the same applies to lists.


What are the main differences between numpy arrays and lists?
1. Type homogeneity: all elements in a numpy array share the same numeric data type, in contrast lists can contain different data types
2. Memory contiguity: a numpy array is stored in a contiguous block of memory. Lists element are not, they can be scattered around in memory.
3. Numpy arrays have fixed length along each dimension, lists do not. E.g. the list `[[1,2],[3,4,5]]` cannot be converted to numpy array, since the first and second 'rows'  of the matrix would have different lengths.

These characteristics make numpy arrays the fastest data structure for computations with vectors, matrices, tensors (intended as multi indices objects),...

**Bottom line: use numpy arrays for manipulating numerical tensors, lists for all the rest.**



In [25]:
heterogeneous_list=['qwerty',a, b, -293.929, [1,2], 1+3j, False] #there is no numpy equivalent for this
print(heterogeneous_list)
print(heterogeneous_list[4][1])

['qwerty', [[1, 2], [3, 4]], array([[1, 2],
       [3, 4]]), -293.929, [1, 2], (1+3j), False]
2


In [26]:
#both lists and numpy arrays suport iteration over elements
a=[1,2,3,4]
b=np.array(a)

for x in b: #or 'for x in a:'
    print(x)

1
2
3
4


In [27]:
#The shape of an array is the length of each dimension. The size is the total number of elements. 'len' gives the length of the first dimension of the array.
b=np.ones([3,2,2])
print(b.shape) 
print(b.size)
print(len(b))

(3, 2, 2)
12
3


In [28]:
#same indexing rules as strings
squares=np.array([1,4,9,16,25,36]) #try with 'squares=[1,4,9,16,25,36]', works the same!
print(squares[2])
print(squares[2:4])
print(squares[0:4:2]) #start:stop:step
print(squares[-3])

9
[ 9 16]
[1 9]
16


In [29]:
#indexing for higher dimensional arrays
a=np.ones([4,3])
print(a)
print("element of a: ",a[1,2]) 
print("first column: ",a[:,0])
print("first row: ", a[0,:])
print("2 by 2 minor: ", a[:2,:2])

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
element of a:  1.0
first column:  [1. 1. 1. 1.]
first row:  [1. 1. 1.]
2 by 2 minor:  [[1. 1.]
 [1. 1.]]


In [30]:
#Notable arrays:
print("zeros\n",np.zeros([3,3])) #3 by 3 matrix of all zeros
print("ones\n",np.ones([3,2,2])) #3 by 2 by 2 tensor of all ones
print("identity\n",np.identity(3))# 3 by 3 identity matrix
print("linspace \n",np.linspace(0,1,11))#(start,stop, number of points) 1D array of evenly spaced values 
print("arange \n",np.arange(0,1,0.1))#(start,stop, step) 1D array of evenly spaced values 
print("random in [0,1)\n",np.random.random([2, 2])) #independent random numbers uniformly distributed in the interval [0,1)

zeros
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones
 [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
identity
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
linspace 
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
arange 
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
random in [0,1)
 [[0.52651439 0.6333376 ]
 [0.64075361 0.95231926]]


#### Arrays operations
The following are common operations on arrays (not available for lists)
**Most operations act in an element-wise manner on arrays**


In [31]:
a=np.array([1,2,3,4])
b=np.array([-np.pi,2.123,1,0])
C=np.array([[1,2],[3,4]])
print(np.sum(a)) #sums all elements
print(a+b) #element-wise addition. WARNING: when applied to lists the '+' operator concatenates the lists.
print(a*b) #element-wise multiplication
print(np.exp(b)) #element-wise exponential
print(C.T) #transpose the matrix
#element-wise operations are particularly fast in arrays compared to lists.

10
[-2.14159265  4.123       4.          4.        ]
[-3.14159265  4.246       3.          0.        ]
[0.04321392 8.35616843 2.71828183 1.        ]
[[1 3]
 [2 4]]


#### Copying

In [32]:
#How NOT to copy an array (or list):
b=np.array([1,2,3,4])
b_fake_copy=b
b_fake_copy[1]=1000
print(b)# the original array was modified when modifying the 'copy'

[   1 1000    3    4]


In [33]:
#How to copy an array (or list):
b=np.array([1,2,3,4])
b_copy=np.copy(b)
b_copy[1]=1000
print(b)# the original array was NOT modified when modifying the copy

[1 2 3 4]


#### Check your shapes!
Shape of numpy arrays can be deceiving and can cause errors in computations.

In [34]:
#in this example a is a one dimensional array, while b is a two dimensional one (i.e. it is a 1 by 4 matrix).
a=np.array([1,2,3,4])
print(a.shape)
b=np.array([[1,2,3,4]])
print(b.shape)
#The extra dimension in b can have unforseen impacts on the operations between the arrays

(4,)
(1, 4)


In [35]:
#Reshape a so that it has the same shape as b
b2=np.reshape(a,[1,4])
print(b2.shape)

#Reshape b so that is has the same shape as a
a2=np.reshape(b,[4])
print(a2.shape)

(1, 4)
(4,)


### Exercise 1: matrix multiplication
Given two matrices $A,B$ their matrix product is the matrix  $$(AB)_{ij}=\sum_k A_{ik}B_{kj}.$$
Code the matrix product
1. Using a for loop
2. Using numpy's built in function

Then compare the time needed to run the two implementations. Which one is faster?

Hint: to measure the execution time of a cell put `%%timeit` at the beginning of the cell

In [36]:
A=np.array([[i+j for i in range(12)] for j in range(4)]) #this is a way of defining lists called 'list comprehensionp
B=np.array([[1 for i in range(4)] for j in range(12)])

In [37]:
#For loop implementation
def matmul_for_loop(A,B):
    pass #your code goes here#
#numnpy's implementation
#your code goes here#

### Exercise 2: matrix powers
Using numpy's matrix multiplication, implement an algorithm that computes the $k$-th power of a square matrix $A$.

In [38]:
A=np.random.random([6,6])
#your code goes here#

### Guided example: multiplying large sparse matrices
The fastest algorithms for multiplying two $n\times n$ matrices takes about $O(n^{2.37\dots})$ time. 

If our matrices are sparse (i.e. only a few elements are nonzero) then faster algorithms exist, but they require a different data structure for representing the matrix.
Scipy, another python library for scientific computing, uses the Compressed Sparse Row (CSR) format. 

Calling $\rho$ the fraction of nonzero elements in the matrix, the time complexity of matrix multiplication using the CSR format is $O(\rho^2 n^3)$, therefore if $\rho$ is small this algorithm is more efficient.
The following cells demonstrate the speedup. 

**Take home messages:** 
1. you should tailor your algorithms to the structure of your data. 
2. **in most situations there already exists a built in function (in numpy or scipy) that does what you want. Look for it before writing your own code.**

In [39]:
#The following code generates a matrix in which on average a fraction rho of the elements are nonzero.
def random_sparse_matrix(n,rho):
    return np.random.random([n,n])*(np.random.random([n,n])<rho)

In [40]:
#generate two random sparse matrices
n=1000
rho=0.1
A=random_sparse_matrix(n,rho)
B=random_sparse_matrix(n,rho)

In [41]:
#convert to CSR format using scipy
from scipy import sparse
A_sparse=sparse.csr_array(A)
B_sparse=sparse.csr_array(B)

In [42]:
%%timeit
A_sparse@B_sparse

53.7 ms ± 2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [43]:
%%timeit
A@B

457 ms ± 48.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Ok, but how does the CSR format really work under the hood? And what about the algorithm to multiply sparse matrices?

1. **Ask ChatGPT**: the prompt "Write python code for implementing the matrix product between sparse matrices. Your algorithm should be optimized for sparse matrices" seems to work pretty well (still be critical of the output and check it).

2. Look it up on wikipedia: [Sparse Matrix](https://en.wikipedia.org/wiki/Sparse_matrix)

Why do we care about sparse matrices? The Pagerank algorithm is based on the webgraph. Is this graph sparse or dense?

#### Exercise
Change the value of `n` in the previous example and rerun the code. 

Should `n` be large or small for the CSR matrix multiplication to have an advantage? Why?